blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://junichiro.github.io/poker-replayer/docs/
    about: Check the API documentation for usage examples
  - name: 🎭 Storybook Examples
    url: https://junichiro.github.io/poker-replayer/storybook/
    about: View interactive component examples
  - name: 💬 Discussions
    url: https://github.com/junichiro/poker-replayer/discussions
    about: Ask questions and discuss ideas with the community